### ISSUE TITLE
checkForRemoteErrors(val) : one node produced an error: could not find function "rmultinom"

### ISSUE THREAD

**Issue by kanefos** [Danko-Lab/TED#22]
Hi authors,

Love the tool, can't want to use. Having issue with getting `run.Ted()` to work. I have formatted my data as laid out in vignette, and started to run, but then encounter this error:

```
Start run... This may take a while 
Loading required package: utils
R Version:  R version 4.1.0 (2021-05-18) 

snowfall 1.84-6.1 initialized (using snow 0.4-4): parallel execution on 1 CPUs.

Error in checkForRemoteErrors(val) : 
  one node produced an error: could not find function "rmultinom"
```

I played with some of [this](https://stackoverflow.com/questions/47197566/r-get-list-and-environment-of-all-variables-and-functions-within-a-given-functi) code to try and get `rmultinom` onto the `snowfall` cluster, but didn't get anywhere. 

Thanks,

**Comment by tinyi** [comment]
Hi Kane,

Thank you for your interest in our work. Can I ask the OS you use?
Linux/Mac OS or Windows? rmultinom should be loaded in base R from stats,
so this issue might be related to the specific R environment.

Best,

Tinyi

**Comment by tinyi** [comment]
I have added stats and utils in the namespace and description. You may try
reinstalling the package.

Best,

Tinyi

**Comment by kanefos** [comment]
Hi Tinyi.
Thanks for such a quick reply, really appreciate it. I'm on macOS Catalina v 10.15.7. 

I reinstalled the packaged, and am not encountering the previous error. However, now I encounter this error message upon running `run.Ted()`.

```
snowfall 1.84-6.1 initialized (using snow 0.4-4): parallel execution on 1 CPUs.

Error in checkForRemoteErrors(val) : 
  one node produced an error: invalid second argument 'size'
```

I am not sure what snowfall does under the hood, but I have not installed any JavaScript or CSS materials on this machine, if this is relevant (no idea). Is there something I need to do to my CPU to make it friendly with snowfall?

Any ideas would be great, thank youKane

**Comment by tinyi** [comment]
Do you have negative values or NA values in your bulk input X?

**Comment by kanefos** [comment]
Aha yes NAs were the issue. My mistake should have looked. Thanks again for all the help, really appreciate it

**Comment by tinyi** [comment]
Hi Kane,

Thank you for your reply. In theory, the run.Ted function should be able to
exclude genes with NA values. Do you mind sending me your bulk matrix or
the exact value that causes the issue, so that I can troubleshoot to adjust
the function that does the filtering to prevent similar issues?

Many thanks.

Best,

Tinyi

**Comment by kanefos** [comment]
Hi Tinyi, sorry I should have edited my comment to say I was also using normalise expression (with negative values), but I simply checked for NAs first then replied. So error on my part understanding required input data. Thanks again for all the help, much appreciated

**Comment by tinyi** [comment]
Hi Kane,

I see.  I will add an assertion for not allowing negative values then.
Thank you for your feedback.

Best,

Tinyi

**Comment by Frank-Xuran** [comment]
My bulk input X donot have negative values or NA values.But, 
Still
Error in checkForRemoteErrors(val) : 
  16 node produced an error: invalid second argument 'size'

**Comment by tinyi** [comment]
> My bulk input X donot have negative values or NA values.But,
> Still
> Error in checkForRemoteErrors(val) :
> 16 node produced an error: invalid second argument 'size'

Hi Frank. Do you mind if sending me your bulk data in Rdata format. I shall be able to help troubleshoot.
