### ISSUE TITLE
Issues with snowfall - parallel execution

### ISSUE THREAD

**Issue by albertopeloso** [Danko-Lab/TED#23]
Hi authors,

thanks for your excellent work and very useful deconvolution tool!
I tried to use your package (I updated it just yesterday after looking at other issues), following the tutorial analysis in the vignette; everything works well until I launch run.Ted function.
I paste here the output code:

```
[1] "removing non-numeric genes..."
[1] "removing outlier genes..."
Number of outlier genes filtered= 6
[1] "aligning reference and mixture"
[1] "run first sampling"
Start run... This may take a while 
R Version:  R version 4.1.2 (2021-11-01) 

snowfall 1.84-6.1 initialized (using snow 0.4-4): parallel execution on 8 CPUs.
```
After this, the CPU is starting working, but with a strange "pattern" looking at the system monitor, then it remains like that (without showing any other output for hours); I'm wondering what does snowfall do inside run.Ted function and if there could be a compatibility problem with the parallelization function, the R version or the system. I'm working on Ubuntu 18.04.6 LTS, AMD Opteron 6344 18 CPU.

Thanks in advance for your kind reply, 
Best, 

Alberto

**Comment by tinyi** [comment]
Hi Alberto,

It indeed will take a while (especially if using only 8 cores). If you are
only going to test the data. you may subset your bulk data using X <-
X[1:20,1:5000] to speed up computation.

We are preparing a new version which will show an estimated run time for
each step.

Best,

Tinyi

**Comment by albertopeloso** [comment]
Thanks a lot for your reply, I will try to subset the X matrix as you suggested, just to give a try with your tutorial data, than go on with my lab's data.
For sure an estimated run time printed on screen would be very useful, so I will wait for next updates of the package.
Best,

Alberto
