### ISSUE TITLE
Relaxation of assumption of identical stroma expression profiles

### ISSUE THREAD

**Issue by kvittingseerup** [Danko-Lab/TED#3]
Hi Tinyi

Again thanks for taking time to answer my questions/speculations. Please just take this as an interest in your great work (which I'm already using :-) ).

Could you share your thoughts about the possibility of relaxing the assumption of identical stroma expression profiles across all samples. My though is that there are cases where this assumption might be violated: 
- In Ivy Gap: when you compare necrotic and proliferative regions of Ivy Gap data.
- In Ivy Gap: when you compare regions far away from blood vessels to regions close to blood vessels

Would it be possible to allow for individual stromal expression profiles constrained by some sort of information sharing either across all or across similar samples?

**Comment by tinyi** [comment]
Yes. In cases where non-malignant cells are highly heterogeneous across
samples, we recommend users to use the initial estimates of cell type
fractions (tcga.ted$res$first.gibbs.res$ theta.merged).

Notice that even the updated theta (tcga.ted$res$ final.gibbs.theta) does
not assume the cell expression profiles are strictly identical across bulk
samples (we did not use frequentist estimates), but rather re-run the
sampling, which is still under the Bayesian setting. In a way, the update
theta would exhibit some shrinkage property by sharing the inferred
expression profiles of non-malignant cell across samples.

Hope this answers your question.

Best,

Tinyi

**Comment by kvittingseerup** [comment]
Hi Tinyi

Thanks (again) for the answers. That is very nice. Sorry I misunderstod the model - I think I was thrown off by the way it is describe some places the manuscript - which make this part it sound more frequentist-like ;-)

**Comment by kvittingseerup** [comment]
Just for my understanding: does this means the primary difference between how tumor and stromal cell types are treated is that stromal cells uses information sharing across samples whereas tumors does not?

**Comment by tinyi** [comment]
Yes. You are correct.

**Comment by kvittingseerup** [comment]
Thanks again for taking time to answer my questions :-)
