### ISSUE TITLE
Also output tumor expression profile

### ISSUE THREAD

**Issue by kvittingseerup** [Danko-Lab/TED#4]
Hi Tinyi

Would it be possible to also output the "pure" tumor expression profiles estimated by TED? Just like we can now get the "pure" stromal expression profiles from ```ted_resut$res$phi.env```.

Cheers
Kristoffer

**Comment by tinyi** [comment]
There are a few versions of tumor expression provided by TED listed as
below. You may also refer to the vignette for details.

> tcga.ted$res$first.gibbs.res$ Znkg # the mean of posterior reads in each
cell type of each bulk sample

> tcga.ted$res$ Zkg.tum.norm # the depth-normalized count of tumor
expression in each bulk sample (the zero count genes adjusted to the same
small value for each sample)

> tcga.ted$res$ Zkg.tum.vst # the variance stabilizing transformed count of
tumor expression in each bulk sample (by the vst function in DESeq2)

**Comment by kvittingseerup** [comment]
Hi Tinyi

That is simply me being to fast. Thanks :-)
